service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  profile: cloudx

package:
  patterns:
    - '!node_modules/**'
    - '!gitignore'
    - '!package-lock.json'

functions:
  getProductsList:
    handler: lambdas/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: lambdas/getProductById.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
