service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  profile: cloudx

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true # auto-packing of external modules

package:
  individually: true

  patterns:
    - '!node_modules/**'
    - '!gitignore'
    - '!package-lock.json'
    - '!package.json'

functions:
  getProductsList:
    handler: lambdas/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: lambdas/getProductById.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
